spring.application.name=SWP391-Group5

# Cấu hình kết nối cơ sở dữ liệu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/freshfruit_v5?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
# Mn thay username và pass mysql nhe, url không cần thay
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none