CREATE TABLE provinces (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    email_verified_at TIMESTAMP
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (role_id) REFERENCES roles(id),
    FOREIGN KEY (assigned_by) REFERENCES users(id)
);

CREATE TABLE user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipient_name VARCHAR(150) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    province_code VARCHAR(20) NOT NULL,
    ward_name VARCHAR(150) NOT NULL,
    address_detail VARCHAR(500) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (province_code) REFERENCES provinces(code)
);

CREATE TABLE shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(2000),
    phone VARCHAR(20) NOT NULL,
    province_code VARCHAR(20) NOT NULL,
    ward_name VARCHAR(150) NOT NULL,
    address_detail VARCHAR(500) NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    operating_status VARCHAR(20) NOT NULL DEFAULT 'CLOSED',
    reviewed_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description CLOB,
    origin VARCHAR(150),
    batch_code VARCHAR(60) NOT NULL,
    received_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    approval_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    selling_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    rejection_reason VARCHAR(1000),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (shop_id, batch_code)
);

CREATE TABLE product_categories (
    product_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, category_id),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(1000) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    UNIQUE (product_id, sort_order),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    sku VARCHAR(80) NOT NULL,
    name VARCHAR(150) NOT NULL,
    specification VARCHAR(1000),
    image_url VARCHAR(1000),
    base_unit_id BIGINT NOT NULL,
    price DECIMAL(19,0) NOT NULL,
    min_order_quantity INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    UNIQUE (shop_id, sku),
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (base_unit_id) REFERENCES units(id)
);

CREATE TABLE variant_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL UNIQUE,
    initial_quantity INT NOT NULL,
    quantity_on_hand INT NOT NULL,
    reserved_quantity INT NOT NULL DEFAULT 0,
    available_quantity INT,
    low_stock_threshold_pct DECIMAL(5,2) NOT NULL DEFAULT 10,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (variant_id) REFERENCES product_variants(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id)
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id),
    variant_id BIGINT NOT NULL REFERENCES product_variants(id),
    quantity INT NOT NULL,
    UNIQUE(cart_id, variant_id)
);

CREATE TABLE checkouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_code VARCHAR(40) NOT NULL UNIQUE,
    request_key VARCHAR(100) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users(id),
    contact_email VARCHAR(254) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    total_amount DECIMAL(19,0) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(40) NOT NULL UNIQUE,
    checkout_id BIGINT NOT NULL REFERENCES checkouts(id),
    shop_id BIGINT NOT NULL REFERENCES shops(id),
    recipient_name VARCHAR(150) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,
    delivery_province_code VARCHAR(20) NOT NULL,
    delivery_province_name VARCHAR(100) NOT NULL,
    delivery_ward_name VARCHAR(150) NOT NULL,
    delivery_address VARCHAR(500) NOT NULL,
    shop_province_code VARCHAR(20) NOT NULL,
    customer_note VARCHAR(1000),
    subtotal DECIMAL(19,0) NOT NULL,
    points_used BIGINT NOT NULL,
    points_discount DECIMAL(19,0) NOT NULL,
    points_subsidy_amount DECIMAL(19,0) NOT NULL,
    qualifying_amount DECIMAL(19,0) NOT NULL,
    points_earned BIGINT NOT NULL,
    shipping_fee DECIMAL(19,0) NOT NULL,
    total_amount DECIMAL(19,0) NOT NULL,
    shop_revenue_amount DECIMAL(19,0) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    delivery_code VARCHAR(60) NOT NULL UNIQUE,
    status VARCHAR(25) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    delivery_status VARCHAR(25) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(id, shop_id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    shop_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    inventory_id BIGINT NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    variant_name VARCHAR(150) NOT NULL,
    sku VARCHAR(80) NOT NULL,
    image_url VARCHAR(1000),
    base_unit_name VARCHAR(50) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(19,0) NOT NULL,
    sale_unit_price DECIMAL(19,0) NOT NULL,
    line_total DECIMAL(19,0) NOT NULL,
    expiry_date DATE NOT NULL,
    allocation_status VARCHAR(20) NOT NULL
);

CREATE TABLE inventory_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    on_hand_delta INT NOT NULL,
    reserved_delta INT NOT NULL,
    on_hand_after INT NOT NULL,
    reserved_after INT NOT NULL,
    event_key VARCHAR(150) NOT NULL UNIQUE,
    created_by BIGINT NOT NULL
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_code VARCHAR(40) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    request_key VARCHAR(100) NOT NULL UNIQUE,
    method VARCHAR(20) NOT NULL,
    amount DECIMAL(19,0) NOT NULL,
    status VARCHAR(20) NOT NULL
);
